import assert from "node:assert/strict";
import { before, beforeEach, describe, it } from "node:test";
import { getApps, initializeApp } from "firebase-admin/app";
import { getFirestore, type Firestore } from "firebase-admin/firestore";
import { completeRunForCallable } from "../src/run/completeRun.js";
import "./completeRunRichSummaryScenarios.js";

const PROJECT_ID = "runiac-functions-test";
const USER_UID = "runner-001";

type CallableRequest = {
  readonly auth?: {
    readonly uid: string;
  };
  readonly data: unknown;
};

type CompletionResult = {
  readonly activityId: string;
  readonly summaryId: string;
  readonly progressionEventId: string;
  readonly validationStatus: string;
  readonly progressionDisplay: {
    readonly xpDelta: number;
    readonly countsTowardLeaderboard: boolean;
    readonly status: string;
    readonly reason: string;
    readonly totalXp?: number;
    readonly level?: number;
    readonly previousTotalXp?: number;
    readonly previousLevel?: number;
    readonly previousLevelProgressPercent?: number;
    readonly levelProgressPercent?: number;
    readonly nextLevelXp?: number | null;
    readonly xpToNextLevel?: number | null;
    readonly previousStreak?: number;
    readonly streak?: number;
  };
};

let firestore: Firestore;

before(() => {
  if (getApps().length === 0) {
    initializeApp({ projectId: PROJECT_ID });
  }

  firestore = getFirestore();
});

beforeEach(async () => {
  await clearCollections([
    "activities",
    "runSummaries",
    "progressionEvents",
    "users",
    "userProfiles",
    "generatedPlans",
    "planProgress",
    "adaptivePlanEstimates",
    "leaderboardContributions",
  ]);
  await firestore.doc(`userProfiles/${USER_UID}`).set({
    nickname: "Test Runner",
    locationLabel: "Jurong East, Singapore",
  });
});

describe("completeRun callable boundary", () => {
  it("fails when auth is missing", async () => {
    await expectRejectsCode(
      () => completeRunForCallable({ data: validPayload() }, firestore),
      "unauthenticated",
    );
  });

  it("rejects activity titles that were not generated by Runiac", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: { ...validPayload(), activityTitle: "My secret route" },
        }),
      "invalid-argument",
    );
  });

  it("writes backend-owned completion artifacts when a minimal payload is valid", async () => {
    const result = await callCompleteRun({ auth: { uid: USER_UID }, data: validPayload() });

    assert.equal(result.validationStatus, "validated");
    assert.equal(result.progressionDisplay.xpDelta, 60);
    assert.equal(result.progressionDisplay.countsTowardLeaderboard, true);
    assert.equal(result.progressionDisplay.status, "awarded");
    assert.equal(result.progressionDisplay.reason, "run_completion_xp_awarded");

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();
    const contribution = await firestore
      .doc(`leaderboardContributions/${USER_UID}_monthly_2026-06`)
      .get();

    assert.equal(activity.get("ownerUid"), USER_UID);
    assert.equal(activity.get("validationStatus"), "validated");
    assert.equal(activity.get("validatedActivityContributionState"), "awarded");
    assert.equal(activity.get("countsTowardProgression"), true);
    assert.equal(activity.get("validationReason"), "run_completion_xp_awarded");
    assert.equal(summary.get("ownerUid"), USER_UID);
    assert.equal(summary.get("title"), "Sunday Morning Run");
    assert.equal(progressionEvent.get("xpDelta"), 60);
    assert.equal(progressionEvent.get("countsTowardLeaderboard"), true);
    assert.equal(contribution.get("ownerUid"), USER_UID);
    assert.equal(contribution.get("periodType"), "monthly");
    assert.equal(contribution.get("periodKey"), "2026-06");
    assert.equal(contribution.get("timezone"), "Asia/Singapore");
    assert.equal(contribution.get("schemaVersion"), 2);
    assert.equal(contribution.get("regionId"), "jurong-east");
    assert.equal(contribution.get("publicAlias"), "Test Runner");
    assert.equal(contribution.get("scoreXp"), 60);
    assert.equal(contribution.get("eligible"), true);
    assert.deepEqual(contribution.get("sourceProgressionEventIds"), [
      result.progressionEventId,
    ]);
  });

  it("awards official XP and level progression for an accepted run", async () => {
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "xp-level-accepted-run",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(result.progressionDisplay.xpDelta, 75);
    assert.equal(result.progressionDisplay.status, "awarded");
    assert.equal(result.progressionDisplay.reason, "run_completion_xp_awarded");
    assert.equal(profile.get("totalXp"), 75);
    assert.equal(profile.get("level"), 1);
    assert.equal(profile.get("divisionKey"), "tier_01");
    assert.equal(profile.get("levelLabel"), "Level 1");
    assert.equal(profile.get("totalXpLabel"), "75 XP");
    assert.equal(profile.get("monthlyXp"), 75);
    assert.equal(profile.get("monthlyXpLabel"), "75 XP");
    assert.equal(progressionEvent.get("xpDelta"), 75);
    assert.equal(progressionEvent.get("baseCompletionXp"), 20);
    assert.equal(progressionEvent.get("distanceXp"), 40);
    assert.equal(progressionEvent.get("durationXp"), 15);
    assert.equal(progressionEvent.get("dailyCapDate"), "2026-06-14");
    assert.equal(progressionEvent.get("dailyXpBefore"), 0);
    assert.equal(progressionEvent.get("dailyXpAfter"), 75);
    assert.equal(progressionEvent.get("previousTotalXp"), 0);
    assert.equal(progressionEvent.get("nextTotalXp"), 75);
    assert.equal(progressionEvent.get("monthlyPeriod"), "2026-06");
    assert.equal(progressionEvent.get("monthlyXpBefore"), 0);
    assert.equal(progressionEvent.get("monthlyXpAfter"), 75);
    assert.equal(progressionEvent.get("previousLevel"), 1);
    assert.equal(progressionEvent.get("nextLevel"), 1);
  });

  it("starts monthly XP from zero across an Asia Singapore month boundary", async () => {
    const juneResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "monthly-rollover-june",
        startedAt: "2026-06-30T14:35:00.000Z",
        completedAt: "2026-06-30T15:00:00.000Z",
      }),
    });
    const julyResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "monthly-rollover-july",
        startedAt: "2026-06-30T16:05:00.000Z",
        completedAt: "2026-06-30T16:30:00.000Z",
      }),
    });

    const juneEvent = await firestore.doc(`progressionEvents/${juneResult.progressionEventId}`).get();
    const julyEvent = await firestore.doc(`progressionEvents/${julyResult.progressionEventId}`).get();
    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();

    assert.equal(juneEvent.get("monthlyPeriod"), "2026-06");
    assert.equal(juneEvent.get("monthlyXpBefore"), 0);
    assert.equal(juneEvent.get("monthlyXpAfter"), 60);
    assert.equal(julyEvent.get("monthlyPeriod"), "2026-07");
    assert.equal(julyEvent.get("monthlyXpBefore"), 0);
    assert.equal(julyEvent.get("monthlyXpAfter"), 60);
    assert.equal(profile.get("totalXp"), 120);
    assert.equal(profile.get("monthlyXp"), 60);
    assert.equal(profile.get("monthlyXpLabel"), "60 XP");
  });

  it("surfaces display-ready progression fields on the fresh and replayed paths", async () => {
    const request = {
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "display-fields-run",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    };

    const fresh = await callCompleteRun(request);
    const replay = await callCompleteRun(request);

    for (const result of [fresh, replay]) {
      const display = result.progressionDisplay;
      assert.equal(display.status, "awarded");
      assert.equal(display.totalXp, 75);
      assert.equal(display.previousTotalXp, 0);
      assert.equal(display.level, 1);
      assert.equal(display.previousLevel, 1);
      assert.equal(display.previousLevelProgressPercent, 0);
      assert.equal(display.levelProgressPercent, 75);
      assert.equal(display.nextLevelXp, 100);
      assert.equal(display.xpToNextLevel, 25);
      assert.equal(display.previousStreak, 0);
      assert.equal(display.streak, 1);
    }

    // Fresh (audit) and replayed (event doc) paths must be identical.
    assert.deepEqual(replay, fresh);

    const progressionEvent = await firestore
      .doc(`progressionEvents/${fresh.progressionEventId}`)
      .get();
    const contribution = await firestore
      .doc(`leaderboardContributions/${USER_UID}_monthly_2026-06`)
      .get();
    assert.equal(progressionEvent.get("previousLevelProgressPercent"), 0);
    assert.equal(progressionEvent.get("nextLevelProgressPercent"), 75);
    assert.equal(progressionEvent.get("nextLevelXpTarget"), 100);
    assert.equal(progressionEvent.get("nextXpToNextLevel"), 25);
    assert.equal(contribution.get("scoreXp"), 75);
    assert.deepEqual(contribution.get("sourceProgressionEventIds"), [
      fresh.progressionEventId,
    ]);
  });

  it("still surfaces streak and total progression fields when no XP is awarded", async () => {
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...lowDataPayload(),
        userConfirmedLowDataSave: true,
      },
    });

    const display = result.progressionDisplay;
    assert.equal(display.status, "not_awarded");
    assert.equal(display.reason, "low_data_no_xp");
    assert.equal(display.xpDelta, 0);
    assert.equal(display.totalXp, 0);
    assert.equal(display.previousTotalXp, 0);
    assert.equal(display.levelProgressPercent, 0);
    assert.equal(display.previousStreak, 0);
    assert.equal(display.streak, 1);
  });

  it("persists valid cadence analysis samples on activity and summary documents", async () => {
    const cadenceAnalysisSeries = validCadenceAnalysisSeries();
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "local-session-cadence-persistence",
        cadenceAnalysisSeries,
      },
    });

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();

    assert.deepEqual(activity.get("cadenceAnalysisSeries"), cadenceAnalysisSeries);
    assert.deepEqual(summary.get("cadenceAnalysisSeries"), cadenceAnalysisSeries);
  });

  it("persists the maximum bounded cadence analysis sample count", async () => {
    const cadenceAnalysisSeries = validCadenceAnalysisSeriesWithSampleCount(720);
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "local-session-cadence-max-samples",
        cadenceAnalysisSeries,
      },
    });

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();

    assert.equal(activity.get("cadenceAnalysisSeries.samples").length, 720);
    assert.deepEqual(activity.get("cadenceAnalysisSeries"), cadenceAnalysisSeries);
    assert.deepEqual(summary.get("cadenceAnalysisSeries"), cadenceAnalysisSeries);
  });

  it("accepts paused duration fields without using wall-clock time as active duration", async () => {
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: pausedRunPayload(),
    });

    assert.equal(result.validationStatus, "validated");

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();

    assert.equal(activity.get("durationSeconds"), 3207);
    assert.equal(activity.get("activeDurationSeconds"), 3207);
    assert.equal(activity.get("elapsedWallSeconds"), 3900);
    assert.equal(activity.get("pausedDurationSeconds"), 693);
    assert.equal(summary.get("durationSeconds"), 3207);
    assert.equal(summary.get("activeDurationSeconds"), 3207);
    assert.equal(summary.get("elapsedWallSeconds"), 3900);
    assert.equal(summary.get("pausedDurationSeconds"), 693);
    assert.equal(summary.get("displayDuration"), "53:27");
    assert.equal(summary.get("displayPace"), "379 sec/km");
  });

  it("rejects inconsistent duration aliases and paused duration math", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...pausedRunPayload(),
            clientRunSessionId: "paused-duration-alias-mismatch",
            durationSeconds: 3208,
          },
        }),
      "invalid-argument",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...pausedRunPayload(),
            clientRunSessionId: "paused-duration-math-mismatch",
            pausedDurationSeconds: 1,
          },
        }),
      "invalid-argument",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...pausedRunPayload(),
            clientRunSessionId: "paused-duration-active-exceeds-elapsed",
            activeDurationSeconds: 4000,
            durationSeconds: 4000,
          },
        }),
      "invalid-argument",
    );
  });

  it("accepts user-confirmed low-data saves and rejects raw low-data payloads", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: lowDataPayload(),
        }),
      "invalid-argument",
    );

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...lowDataPayload(),
        userConfirmedLowDataSave: true,
      },
    });

    assert.equal(result.validationStatus, "validated");
    assert.equal(result.progressionDisplay.xpDelta, 0);
    assert.equal(result.progressionDisplay.countsTowardLeaderboard, false);
    assert.equal(result.progressionDisplay.status, "not_awarded");
    assert.equal(result.progressionDisplay.reason, "low_data_no_xp");

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(activity.exists, true);
    assert.equal(summary.exists, true);
    assert.equal(progressionEvent.exists, true);
    assert.equal(activity.get("distanceMeters"), 0);
    assert.equal(activity.get("averagePaceSecondsPerKm"), 0);
    assert.equal(summary.get("distanceMeters"), 0);
    assert.equal(summary.get("averagePaceSecondsPerKm"), 0);
    assert.equal(progressionEvent.get("xpDelta"), 0);
    assert.equal(progressionEvent.get("countsTowardLeaderboard"), false);
  });

  it("rejects confirmed positive-distance saves with zero pace", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            clientRunSessionId: "positive-distance-zero-pace",
            userConfirmedLowDataSave: true,
            avgPaceSecondsPerKm: 0,
          },
        }),
      "invalid-argument",
    );
  });

  it("completeRun writes owner scoped run summaries", async () => {
    const result = await callCompleteRun({ auth: { uid: "alice" }, data: validPayload() });

    const activity = await firestore.doc(`activities/${result.activityId}`).get();
    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(activity.get("ownerUid"), "alice");
    assert.equal(summary.get("ownerUid"), "alice");
    assert.equal(summary.get("activityId"), result.activityId);
    assert.equal(progressionEvent.get("ownerUid"), "alice");
  });

  it("completeRun scopes deterministic ids by uid", async () => {
    const aliceResult = await callCompleteRun({ auth: { uid: "alice" }, data: validPayload() });
    const bobResult = await callCompleteRun({ auth: { uid: "bob" }, data: validPayload() });

    assert.notEqual(aliceResult.activityId, bobResult.activityId);
    assert.notEqual(aliceResult.summaryId, bobResult.summaryId);
    assert.notEqual(aliceResult.progressionEventId, bobResult.progressionEventId);
  });

  it("completeRun gives distinct artifacts to distinct client run session ids", async () => {
    const firstResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "local-run-20260618-080000-a",
      },
    });
    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "local-run-20260618-090000-b",
        startedAt: "2026-06-14T10:00:00.000Z",
        completedAt: "2026-06-14T10:25:00.000Z",
      },
    });

    assert.notEqual(firstResult.activityId, secondResult.activityId);
    assert.notEqual(firstResult.summaryId, secondResult.summaryId);
    assert.notEqual(
      firstResult.progressionEventId,
      secondResult.progressionEventId,
    );
    assert.equal(await countDocuments("activities"), 2);
    assert.equal(await countDocuments("runSummaries"), 2);
    assert.equal(await countDocuments("progressionEvents"), 2);
  });

  it("creates and updates backend-owned adaptive plan estimates for valid runs", async () => {
    const firstResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "adaptive-estimate-first-valid-run",
      },
    });

    const firstEstimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.equal(firstEstimate.exists, true);
    assert.equal(firstEstimate.get("ownerUid"), USER_UID);
    assert.equal(firstEstimate.get("latestActivityId"), firstResult.activityId);
    assert.equal(firstEstimate.get("completedRunCount"), 1);
    assert.equal(firstEstimate.get("lastRunCompletedAt"), "2026-06-14T09:25:00.000Z");
    assert.equal(firstEstimate.get("lastRunDistanceMeters"), 3200);
    assert.equal(firstEstimate.get("lastRunDurationSeconds"), 1500);
    assert.equal(firstEstimate.get("averageRecentPaceSecondsPerKm"), 469);
    assert.equal(firstEstimate.get("readinessBand"), "learning");
    assert.equal(firstEstimate.get("source"), "completeRun");
    assert.equal(firstEstimate.get("updatedAt"), "2026-06-14T09:25:00.000Z");

    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "adaptive-estimate-second-valid-run",
        startedAt: "2026-06-16T09:00:00.000Z",
        completedAt: "2026-06-16T09:27:21.000Z",
        durationSeconds: 1641,
        distanceMeters: 3500,
        avgPaceSecondsPerKm: 469,
      }),
    });

    const updatedEstimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.equal(updatedEstimate.get("ownerUid"), USER_UID);
    assert.equal(updatedEstimate.get("latestActivityId"), secondResult.activityId);
    assert.notEqual(updatedEstimate.get("latestActivityId"), firstResult.activityId);
    assert.equal(updatedEstimate.get("completedRunCount"), 2);
    assert.equal(updatedEstimate.get("lastRunCompletedAt"), "2026-06-16T09:27:21.000Z");
    assert.equal(updatedEstimate.get("lastRunDistanceMeters"), 3500);
    assert.equal(updatedEstimate.get("lastRunDurationSeconds"), 1641);
    assert.equal(updatedEstimate.get("averageRecentPaceSecondsPerKm"), 469);
    assert.equal(updatedEstimate.get("readinessBand"), "learning");
    assert.equal(updatedEstimate.get("source"), "completeRun");
    assert.equal(updatedEstimate.get("updatedAt"), "2026-06-16T09:27:21.000Z");
  });

  it("does not double count adaptive estimate learning for duplicate clientRunSessionId values", async () => {
    const payload = runPayloadForSession({
      clientRunSessionId: "adaptive-estimate-duplicate-session",
      startedAt: "2026-06-14T09:00:00.000Z",
      completedAt: "2026-06-14T09:25:00.000Z",
    });

    const firstResult = await callCompleteRun({ auth: { uid: USER_UID }, data: payload });
    const secondResult = await callCompleteRun({ auth: { uid: USER_UID }, data: payload });

    const estimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.deepEqual(secondResult, firstResult);
    assert.equal(estimate.exists, true);
    assert.equal(estimate.get("latestActivityId"), firstResult.activityId);
    assert.equal(estimate.get("completedRunCount"), 1);
    assert.equal(estimate.get("lastRunCompletedAt"), "2026-06-14T09:25:00.000Z");
    assert.equal(estimate.get("lastRunDistanceMeters"), 3200);
    assert.equal(estimate.get("lastRunDurationSeconds"), 1500);
    assert.equal(estimate.get("averageRecentPaceSecondsPerKm"), 469);
    assert.equal(estimate.get("readinessBand"), "learning");
    assert.equal(estimate.get("source"), "completeRun");
    assert.equal(estimate.get("updatedAt"), "2026-06-14T09:25:00.000Z");
  });

  it("keeps confirmed low-data adaptive estimates conservative without a positive pace estimate", async () => {
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...lowDataPayload(),
        clientRunSessionId: "adaptive-estimate-confirmed-low-data",
        userConfirmedLowDataSave: true,
      },
    });

    const estimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.equal(estimate.exists, true);
    assert.equal(estimate.get("ownerUid"), USER_UID);
    assert.equal(estimate.get("latestActivityId"), result.activityId);
    assert.equal(estimate.get("completedRunCount"), 1);
    assert.equal(estimate.get("lastRunCompletedAt"), "2026-06-14T09:00:02.000Z");
    assert.equal(estimate.get("lastRunDistanceMeters"), 0);
    assert.equal(estimate.get("lastRunDurationSeconds"), 2);
    assert.equal(estimate.get("averageRecentPaceSecondsPerKm"), 0);
    assert.equal(estimate.get("readinessBand"), "conservative");
    assert.equal(estimate.get("source"), "completeRun");
    assert.equal(estimate.get("updatedAt"), "2026-06-14T09:00:02.000Z");
  });

  it("does not let low-data adaptive estimates dilute the next positive pace estimate", async () => {
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...lowDataPayload(),
        clientRunSessionId: "adaptive-estimate-low-data-before-positive-run",
        userConfirmedLowDataSave: true,
      },
    });

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "adaptive-estimate-positive-run-after-low-data",
      },
    });

    const estimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.equal(estimate.exists, true);
    assert.equal(estimate.get("latestActivityId"), result.activityId);
    assert.equal(estimate.get("completedRunCount"), 2);
    assert.equal(estimate.get("averageRecentPaceSecondsPerKm"), 469);
    assert.equal(estimate.get("readinessBand"), "learning");
  });

  it("does not let low-data adaptive estimates erase an existing positive pace estimate", async () => {
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "adaptive-estimate-positive-run-before-low-data",
      },
    });

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...lowDataPayload(),
        clientRunSessionId: "adaptive-estimate-low-data-after-positive-run",
        userConfirmedLowDataSave: true,
      },
    });

    const estimate = await firestore.doc(`adaptivePlanEstimates/${USER_UID}`).get();

    assert.equal(estimate.exists, true);
    assert.equal(estimate.get("latestActivityId"), result.activityId);
    assert.equal(estimate.get("completedRunCount"), 2);
    assert.equal(estimate.get("averageRecentPaceSecondsPerKm"), 469);
    assert.equal(estimate.get("positivePaceRunCount"), 1);
    assert.equal(estimate.get("readinessBand"), "conservative");
  });

  it("persists backend-owned streak state and progression audit for consecutive run days", async () => {
    const firstResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-day-20260614",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:25:00.000Z",
      }),
    });
    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-day-20260615",
        startedAt: "2026-06-15T09:00:00.000Z",
        completedAt: "2026-06-15T09:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const firstProgressionEvent = await firestore.doc(`progressionEvents/${firstResult.progressionEventId}`).get();
    const secondProgressionEvent = await firestore.doc(`progressionEvents/${secondResult.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 2);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-15");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-15T09:25:00.000Z");
    assert.equal(firstProgressionEvent.get("previousStreak"), 0);
    assert.equal(firstProgressionEvent.get("nextStreak"), 1);
    assert.equal(firstProgressionEvent.get("previousStreakRunDate"), null);
    assert.equal(firstProgressionEvent.get("nextStreakRunDate"), "2026-06-14");
    assert.equal(secondProgressionEvent.get("previousStreak"), 1);
    assert.equal(secondProgressionEvent.get("nextStreak"), 2);
    assert.equal(secondProgressionEvent.get("previousStreakRunDate"), "2026-06-14");
    assert.equal(secondProgressionEvent.get("nextStreakRunDate"), "2026-06-15");
  });

  it("continues streak across a scheduled generated-plan rest day", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-mon-easy-run",
        dayLabel: "Mon",
        durationMinutes: 25,
      }),
      durationWorkout({
        scheduledWorkoutId: "week-1-tue-easy-run",
        dayLabel: "Tue",
        durationMinutes: 25,
      }),
      restWorkout({
        scheduledWorkoutId: "week-1-wed-rest-day",
        dayLabel: "Wed",
      }),
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-rest-bridge-day-one",
        startedAt: "2026-06-15T09:00:00.000Z",
        completedAt: "2026-06-15T09:25:00.000Z",
      }),
    });
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-rest-bridge-day-two",
        startedAt: "2026-06-16T09:00:00.000Z",
        completedAt: "2026-06-16T09:25:00.000Z",
      }),
    });

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-rest-bridge-after-rest",
        startedAt: "2026-06-18T09:00:00.000Z",
        completedAt: "2026-06-18T09:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 3);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-18");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-18T09:25:00.000Z");
    assert.equal(progressionEvent.get("previousStreak"), 2);
    assert.equal(progressionEvent.get("nextStreak"), 3);
    assert.equal(progressionEvent.get("previousStreakRunDate"), "2026-06-16");
    assert.equal(progressionEvent.get("nextStreakRunDate"), "2026-06-18");
  });

  it("does not double increment streak state for duplicate clientRunSessionId values", async () => {
    const payload = runPayloadForSession({
      clientRunSessionId: "streak-duplicate-session",
      startedAt: "2026-06-14T09:00:00.000Z",
      completedAt: "2026-06-14T09:25:00.000Z",
    });

    const firstResult = await callCompleteRun({ auth: { uid: USER_UID }, data: payload });
    const secondResult = await callCompleteRun({ auth: { uid: USER_UID }, data: payload });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${firstResult.progressionEventId}`).get();

    assert.deepEqual(secondResult, firstResult);
    assert.equal(profile.get("streakCount"), 1);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-14");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-14T09:25:00.000Z");
    assert.equal(progressionEvent.get("previousStreak"), 0);
    assert.equal(progressionEvent.get("nextStreak"), 1);
    assert.equal(progressionEvent.get("previousStreakRunDate"), null);
    assert.equal(progressionEvent.get("nextStreakRunDate"), "2026-06-14");
    assert.equal(await countDocuments("progressionEvents"), 1);
  });

  it("does not increment streak state beyond one for a second same-day valid run", async () => {
    const firstResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-same-day-first",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:25:00.000Z",
      }),
    });
    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-same-day-second",
        startedAt: "2026-06-14T14:00:00.000Z",
        completedAt: "2026-06-14T14:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const firstProgressionEvent = await firestore.doc(`progressionEvents/${firstResult.progressionEventId}`).get();
    const secondProgressionEvent = await firestore.doc(`progressionEvents/${secondResult.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 1);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-14");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-14T14:25:00.000Z");
    assert.equal(firstProgressionEvent.get("previousStreak"), 0);
    assert.equal(firstProgressionEvent.get("nextStreak"), 1);
    assert.equal(firstProgressionEvent.get("previousStreakRunDate"), null);
    assert.equal(firstProgressionEvent.get("nextStreakRunDate"), "2026-06-14");
    assert.equal(secondProgressionEvent.get("previousStreak"), 1);
    assert.equal(secondProgressionEvent.get("nextStreak"), 1);
    assert.equal(secondProgressionEvent.get("previousStreakRunDate"), "2026-06-14");
    assert.equal(secondProgressionEvent.get("nextStreakRunDate"), "2026-06-14");
  });

  it("restarts streak state after a missed-day gap", async () => {
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-gap-first",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:25:00.000Z",
      }),
    });
    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-gap-second",
        startedAt: "2026-06-17T09:00:00.000Z",
        completedAt: "2026-06-17T09:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const secondProgressionEvent = await firestore.doc(`progressionEvents/${secondResult.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 1);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-17");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-17T09:25:00.000Z");
    assert.equal(secondProgressionEvent.get("previousStreak"), 1);
    assert.equal(secondProgressionEvent.get("nextStreak"), 1);
    assert.equal(secondProgressionEvent.get("previousStreakRunDate"), "2026-06-14");
    assert.equal(secondProgressionEvent.get("nextStreakRunDate"), "2026-06-17");
  });

  it("does not regress persisted streak state when an older valid run syncs later", async () => {
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-current-first",
        startedAt: "2026-06-14T09:00:00.000Z",
        completedAt: "2026-06-14T09:25:00.000Z",
      }),
    });
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-current-second",
        startedAt: "2026-06-15T09:00:00.000Z",
        completedAt: "2026-06-15T09:25:00.000Z",
      }),
    });
    const olderResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-late-older-sync",
        startedAt: "2026-06-13T09:00:00.000Z",
        completedAt: "2026-06-13T09:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const olderProgressionEvent = await firestore.doc(`progressionEvents/${olderResult.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 2);
    assert.equal(profile.get("lastStreakRunDate"), "2026-06-15");
    assert.equal(profile.get("streakUpdatedAt"), "2026-06-15T09:25:00.000Z");
    assert.equal(olderProgressionEvent.get("previousStreak"), 2);
    assert.equal(olderProgressionEvent.get("nextStreak"), 2);
    assert.equal(olderProgressionEvent.get("previousStreakRunDate"), "2026-06-15");
    assert.equal(olderProgressionEvent.get("nextStreakRunDate"), "2026-06-15");
  });

  it("recalculates streak from validated activities after the generated plan creation date", async () => {
    await firestore.doc(`userProfiles/${USER_UID}`).set({
      streakCount: 17,
      lastStreakRunDate: "2026-07-04",
      streakUpdatedAt: "2026-07-04T09:25:00.000Z",
    });
    await firestore.doc(`generatedPlans/${USER_UID}`).set({
      createdAt: "2026-07-05T00:05:00.000Z",
      updatedAt: "2026-07-05T00:05:00.000Z",
    });
    await firestore.doc("activities/pre-plan-run").set({
      ownerUid: USER_UID,
      activityType: "run",
      validationStatus: "validated",
      endedAt: "2026-07-04T09:25:00.000Z",
    });

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "streak-after-onboarding-plan",
        startedAt: "2026-07-05T09:00:00.000Z",
        completedAt: "2026-07-05T09:25:00.000Z",
      }),
    });

    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(profile.get("streakCount"), 1);
    assert.equal(profile.get("lastStreakRunDate"), "2026-07-05");
    assert.equal(profile.get("streakUpdatedAt"), "2026-07-05T09:25:00.000Z");
    assert.equal(progressionEvent.get("previousStreak"), 0);
    assert.equal(progressionEvent.get("nextStreak"), 1);
    assert.equal(progressionEvent.get("previousStreakRunDate"), null);
    assert.equal(progressionEvent.get("nextStreakRunDate"), "2026-07-05");
  });

  it("writes plan progress for an explicitly linked duration workout only after the full objective is completed", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "plan-thu-under-duration",
        startedAt: "2026-06-18T09:00:00.000Z",
        completedAt: "2026-06-18T09:20:00.000Z",
        durationSeconds: 1200,
        distanceMeters: 2500,
        avgPaceSecondsPerKm: 480,
      }),
    });
    assert.equal(await countDocuments("activities"), 1);
    assert.equal((await firestore.doc(`planProgress/${USER_UID}`).get()).exists, false);

    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-thu-full-duration",
          startedAt: "2026-06-18T10:00:00.000Z",
          completedAt: "2026-06-18T10:25:00.000Z",
        }),
        scheduledWorkoutId: "week-1-thu-easy-run",
      },
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();
    const progressionEvent = await firestore.doc(`progressionEvents/${result.progressionEventId}`).get();

    assert.equal(progress.get("ownerUid"), USER_UID);
    assert.equal(progress.get("completedWorkoutCount"), 1);
    assert.equal(progress.get("updatedAt"), "2026-06-18T10:25:00.000Z");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.activityId"), result.activityId);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.clientRunSessionId"), "plan-thu-full-duration");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.completedAt"), "2026-06-18T10:25:00.000Z");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.objectiveKind"), "duration");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.objectiveSeconds"), 1500);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.matchedBy"), "explicit");
    assert.equal(progressionEvent.get("plannedWorkoutRecorded"), true);
    assert.equal(progressionEvent.get("plannedWorkoutBonusApplied"), true);
    assert.equal(progressionEvent.get("planCompletionBonusXp"), 20);
    assert.equal(progressionEvent.get("xpDelta"), 80);
  });

  it("auto-matches only the active generated workout on the run completedAt date", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-tue-easy-run",
        dayLabel: "Tue",
        durationMinutes: 20,
      }),
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "plan-thu-auto-match",
        startedAt: "2026-06-18T09:00:00.000Z",
        completedAt: "2026-06-18T09:25:00.000Z",
      }),
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();

    assert.equal(progress.get("completedWorkoutCount"), 1);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.clientRunSessionId"), "plan-thu-auto-match");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.matchedBy"), "date");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-tue-easy-run"), undefined);
  });

  it("does not use closest-similarity or first-incomplete matching when no workout is active on the completedAt date", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-tue-easy-run",
        dayLabel: "Tue",
        durationMinutes: 25,
      }),
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "plan-wed-no-auto-match",
        startedAt: "2026-06-17T09:00:00.000Z",
        completedAt: "2026-06-17T09:25:00.000Z",
      }),
    });

    assert.equal(await countDocuments("activities"), 1);
    assert.equal((await firestore.doc(`planProgress/${USER_UID}`).get()).exists, false);
  });

  it("keeps the first valid completion for a scheduled workout permanently", async () => {
    await writeGeneratedPlanWithWorkouts([
      distanceWorkout({
        scheduledWorkoutId: "week-1-sat-long-run",
        dayLabel: "Sat",
        targetDistanceMeters: 3000,
      }),
    ]);

    const firstResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-sat-distance-first",
          startedAt: "2026-06-20T09:00:00.000Z",
          completedAt: "2026-06-20T09:25:00.000Z",
        }),
        scheduledWorkoutId: "week-1-sat-long-run",
      },
    });
    const secondResult = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-sat-distance-later",
          startedAt: "2026-06-20T10:00:00.000Z",
          completedAt: "2026-06-20T10:30:00.000Z",
        }),
        distanceMeters: 5000,
        scheduledWorkoutId: "week-1-sat-long-run",
      },
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();
    const firstProgressionEvent = await firestore.doc(`progressionEvents/${firstResult.progressionEventId}`).get();
    const secondProgressionEvent = await firestore.doc(`progressionEvents/${secondResult.progressionEventId}`).get();

    assert.equal(await countDocuments("activities"), 2);
    assert.equal(progress.get("completedWorkoutCount"), 1);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-sat-long-run.activityId"), firstResult.activityId);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-sat-long-run.clientRunSessionId"), "plan-sat-distance-first");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-sat-long-run.actualDistanceMeters"), 3200);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-sat-long-run.objectiveKind"), "distance");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-sat-long-run.objectiveMeters"), 3000);
    assert.equal(firstProgressionEvent.get("plannedWorkoutRecorded"), true);
    assert.equal(firstProgressionEvent.get("planCompletionBonusXp"), 20);
    assert.equal(secondProgressionEvent.get("plannedWorkoutRecorded"), false);
    assert.equal(secondProgressionEvent.get("planCompletionBonusXp"), 0);
  });

  it("does not trust client plan enrollment ids to duplicate completion progress", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-enrollment-first",
          startedAt: "2026-06-18T09:00:00.000Z",
          completedAt: "2026-06-18T09:25:00.000Z",
        }),
        planEnrollmentId: "generated-plan-001",
        scheduledWorkoutId: "week-1-thu-easy-run",
      },
    });
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-enrollment-second",
          startedAt: "2026-06-18T10:00:00.000Z",
          completedAt: "2026-06-18T10:25:00.000Z",
        }),
        planEnrollmentId: "generated-plan-v2",
        scheduledWorkoutId: "week-1-thu-easy-run",
      },
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();

    assert.equal(progress.get("completedWorkoutCount"), 1);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.planEnrollmentId"), "generated-plan-001");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.scheduledWorkoutId"), "week-1-thu-easy-run");
  });

  it("keeps progress separate when a server-trusted generated plan id changes", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-easy-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "server-plan-first",
          startedAt: "2026-06-18T09:00:00.000Z",
          completedAt: "2026-06-18T09:25:00.000Z",
        }),
        scheduledWorkoutId: "week-1-thu-easy-run",
      },
    });
    await writeGeneratedPlanWithWorkouts(
      [
        durationWorkout({
          scheduledWorkoutId: "week-1-thu-easy-run",
          dayLabel: "Thu",
          durationMinutes: 25,
        }),
      ],
      { planId: "generated-plan-002" },
    );
    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "server-plan-second",
          startedAt: "2026-06-18T10:00:00.000Z",
          completedAt: "2026-06-18T10:25:00.000Z",
        }),
        scheduledWorkoutId: "week-1-thu-easy-run",
      },
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();

    assert.equal(progress.get("completedWorkoutCount"), 2);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-easy-run.clientRunSessionId"), "server-plan-first");
    assert.equal(progress.get("workouts.generated-plan-002__week-1-thu-easy-run.clientRunSessionId"), "server-plan-second");
  });

  it("uses actual completedAt date for late offline uploads instead of upload time", async () => {
    await writeGeneratedPlanWithWorkouts([
      durationWorkout({
        scheduledWorkoutId: "week-1-thu-offline-run",
        dayLabel: "Thu",
        durationMinutes: 25,
      }),
    ]);

    await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...runPayloadForSession({
          clientRunSessionId: "plan-late-offline-upload",
          startedAt: "2026-06-18T22:30:00.000Z",
          completedAt: "2026-06-18T22:55:00.000Z",
        }),
        deviceRecordedAt: "2026-06-19T08:00:00.000Z",
      },
    });

    const progress = await firestore.doc(`planProgress/${USER_UID}`).get();

    assert.equal(progress.get("completedWorkoutCount"), 1);
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-offline-run.clientRunSessionId"), "plan-late-offline-upload");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-offline-run.completedAt"), "2026-06-18T22:55:00.000Z");
    assert.equal(progress.get("workouts.generated-plan-001__week-1-thu-offline-run.matchedBy"), "date");
  });

  it("fails when a required field is missing", async () => {
    const payload = validPayloadWithout("distanceMeters");

    await expectRejectsCode(
      () => callCompleteRun({ auth: { uid: USER_UID }, data: payload }),
      "invalid-argument",
    );
  });

  it("fails when completedAt is not after startedAt", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            completedAt: "2026-06-14T09:00:00.000Z",
          },
        }),
      "invalid-argument",
    );
  });

  it("fails when timestamps are not strict UTC ISO strings", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            startedAt: "June 14 2026 09:00",
          },
        }),
      "invalid-argument",
    );
  });

  it("fails when metrics exceed emulator skeleton safety limits", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            distanceMeters: 1_000_000,
          },
        }),
      "invalid-argument",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            avgPaceSecondsPerKm: 1,
          },
        }),
      "invalid-argument",
    );
  });

  it("rejects protected backend-owned fields", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            xp: 100,
            validationStatus: "validated",
            countsTowardProgression: true,
            leaderboardScore: 100,
          },
        }),
      "invalid-argument",
    );
  });

  it("rejects malformed cadence analysis payloads", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            clientRunSessionId: "cadence-malformed-non-array-samples",
            cadenceAnalysisSeries: {
              ...validCadenceAnalysisSeries(),
              samples: "not-samples",
            },
          },
        }),
      "invalid-argument",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            clientRunSessionId: "cadence-malformed-out-of-range-sample",
            cadenceAnalysisSeries: {
              ...validCadenceAnalysisSeries(),
              samples: [
                { elapsedSeconds: 30, cadenceSpm: 241, status: "accepted" },
              ],
            },
          },
        }),
      "invalid-argument",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            clientRunSessionId: "cadence-malformed-too-many-samples",
            cadenceAnalysisSeries: validCadenceAnalysisSeriesWithSampleCount(721),
          },
        }),
      "invalid-argument",
    );

    for (const [clientRunSessionId, samples] of [
      [
        "cadence-malformed-duplicate-elapsed",
        [
          { elapsedSeconds: 30, cadenceSpm: 120, status: "accepted" },
          { elapsedSeconds: 30, cadenceSpm: 122, status: "accepted" },
        ],
      ],
      [
        "cadence-malformed-decreasing-elapsed",
        [
          { elapsedSeconds: 60, cadenceSpm: 120, status: "accepted" },
          { elapsedSeconds: 30, cadenceSpm: 122, status: "accepted" },
        ],
      ],
      [
        "cadence-malformed-beyond-duration",
        [{ elapsedSeconds: 1501, cadenceSpm: 120, status: "accepted" }],
      ],
    ] as const) {
      await expectRejectsCode(
        () =>
          callCompleteRun({
            auth: { uid: USER_UID },
            data: {
              ...validPayload(),
              clientRunSessionId,
              cadenceAnalysisSeries: {
                ...validCadenceAnalysisSeries(),
                samples,
              },
            },
          }),
        "invalid-argument",
      );
    }

    assert.equal(await countDocuments("activities"), 0);
    assert.equal(await countDocuments("runSummaries"), 0);
    assert.equal(await countDocuments("progressionEvents"), 0);
  });

  it("accepts cadence samples at the shared 40 through 240 spm boundaries", async () => {
    const boundarySeries = {
      source: "phoneSensorEstimated",
      confidence: "low",
      samples: [
        { elapsedSeconds: 30, cadenceSpm: 40, status: "accepted" },
        { elapsedSeconds: 60, cadenceSpm: 240, status: "accepted" },
      ],
    };
    const result = await callCompleteRun({
      auth: { uid: USER_UID },
      data: {
        ...validPayload(),
        clientRunSessionId: "cadence-shared-boundary-contract",
        cadenceAnalysisSeries: boundarySeries,
      },
    });

    const summary = await firestore.doc(`runSummaries/${result.summaryId}`).get();
    assert.deepEqual(summary.get("cadenceAnalysisSeries"), boundarySeries);
  });

  it("is idempotent for duplicate clientRunSessionId values", async () => {
    const first = await callCompleteRun({ auth: { uid: USER_UID }, data: validPayload() });
    const second = await callCompleteRun({ auth: { uid: USER_UID }, data: validPayload() });
    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();

    assert.deepEqual(second, first);
    assert.equal(await countDocuments("activities"), 1);
    assert.equal(await countDocuments("runSummaries"), 1);
    assert.equal(await countDocuments("progressionEvents"), 1);
    assert.equal(profile.get("totalXp"), 60);
  });

  it("caps same-day XP at 200 using the Asia Singapore local date", async () => {
    const first = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "daily-cap-first",
        startedAt: "2026-06-14T08:00:00.000Z",
        completedAt: "2026-06-14T08:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    });
    const second = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "daily-cap-second",
        startedAt: "2026-06-14T10:00:00.000Z",
        completedAt: "2026-06-14T10:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    });
    const third = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "daily-cap-third",
        startedAt: "2026-06-14T12:00:00.000Z",
        completedAt: "2026-06-14T12:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    });
    const exhausted = await callCompleteRun({
      auth: { uid: USER_UID },
      data: runPayloadForSession({
        clientRunSessionId: "daily-cap-exhausted",
        startedAt: "2026-06-14T14:00:00.000Z",
        completedAt: "2026-06-14T14:31:00.000Z",
        durationSeconds: 1860,
        distanceMeters: 4200,
        avgPaceSecondsPerKm: 443,
      }),
    });

    const firstEvent = await firestore.doc(`progressionEvents/${first.progressionEventId}`).get();
    const secondEvent = await firestore.doc(`progressionEvents/${second.progressionEventId}`).get();
    const thirdEvent = await firestore.doc(`progressionEvents/${third.progressionEventId}`).get();
    const exhaustedEvent = await firestore.doc(`progressionEvents/${exhausted.progressionEventId}`).get();
    const profile = await firestore.doc(`userProfiles/${USER_UID}`).get();

    assert.equal(firstEvent.get("xpDelta"), 75);
    assert.equal(secondEvent.get("xpDelta"), 75);
    assert.equal(thirdEvent.get("xpDelta"), 50);
    assert.equal(thirdEvent.get("dailyXpBefore"), 150);
    assert.equal(thirdEvent.get("dailyXpAfter"), 200);
    assert.equal(thirdEvent.get("dailyCapApplied"), true);
    assert.equal(thirdEvent.get("dailyCapDate"), "2026-06-14");
    assert.equal(exhausted.progressionDisplay.xpDelta, 0);
    assert.equal(exhausted.progressionDisplay.reason, "daily_cap_reached");
    assert.equal(exhaustedEvent.get("dailyXpBefore"), 200);
    assert.equal(exhaustedEvent.get("dailyXpAfter"), 200);
    assert.equal(profile.get("totalXp"), 200);
    assert.equal(profile.get("monthlyXp"), 200);
    assert.equal(profile.get("monthlyXpLabel"), "200 XP");
  });

  it("rejects duplicate clientRunSessionId values with changed payload content", async () => {
    await callCompleteRun({ auth: { uid: USER_UID }, data: validPayload() });

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            completedAt: "2026-06-14T09:30:00.000Z",
            durationSeconds: 1800,
            distanceMeters: 4000,
          },
        }),
      "already-exists",
    );

    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            routeLabel: "Changed route label",
          },
        }),
      "already-exists",
    );
  });

  it("gives premium users no XP, rank, or leaderboard advantage", async () => {
    await firestore.doc(`users/${USER_UID}`).set({
      subscriptionStatus: "premium",
    });
    await firestore.doc(`userProfiles/${USER_UID}`).set({
      xp: 999,
      rank: 3,
      leaderboardScore: 999,
    });

    const result = await callCompleteRun({ auth: { uid: USER_UID }, data: validPayload() });
    const profileAfter = await firestore.doc(`userProfiles/${USER_UID}`).get();

    assert.equal(result.progressionDisplay.xpDelta, 0);
    assert.equal(result.progressionDisplay.countsTowardLeaderboard, false);
    assert.equal(result.progressionDisplay.status, "not_awarded");
    assert.equal(result.progressionDisplay.reason, "premium_no_progression");
    assert.equal(profileAfter.get("xp"), 999);
    assert.equal(profileAfter.get("rank"), 3);
    assert.equal(profileAfter.get("leaderboardScore"), 999);
    assert.equal(profileAfter.get("totalXp"), 0);
    assert.equal(profileAfter.get("level"), 1);
    assert.equal(profileAfter.get("levelProgressPercent"), 0);
    assert.equal(profileAfter.get("monthlyXp"), 0);
    assert.equal(profileAfter.get("monthlyXpLabel"), "0 XP");
  });

  it("rejects precise route traces and does not persist them", async () => {
    await expectRejectsCode(
      () =>
        callCompleteRun({
          auth: { uid: USER_UID },
          data: {
            ...validPayload(),
            routeTrace: [{ coordinate: "synthetic-private-route-point" }],
          },
        }),
      "invalid-argument",
    );

    assert.equal(await countDocuments("activities"), 0);
    assert.equal(await countDocuments("runSummaries"), 0);
    assert.equal(await countDocuments("progressionEvents"), 0);
  });
});

async function callCompleteRun(request: CallableRequest): Promise<CompletionResult> {
  return completeRunForCallable(request, firestore);
}

function validPayload(): Record<string, unknown> {
  return {
    clientRunSessionId: "local-session-001",
    startedAt: "2026-06-14T09:00:00.000Z",
    completedAt: "2026-06-14T09:25:00.000Z",
    durationSeconds: 1500,
    distanceMeters: 3200,
    avgPaceSecondsPerKm: 469,
    source: "mobile",
    routePrivacy: "private",
    activityTitle: "Sunday Morning Run",
  };
}

function validCadenceAnalysisSeries(): Record<string, unknown> {
  return {
    source: "phoneSensorEstimated",
    confidence: "low",
    samples: [
      { elapsedSeconds: 30, cadenceSpm: 95, status: "accepted" },
      { elapsedSeconds: 90, cadenceSpm: 118, status: "accepted" },
      { elapsedSeconds: 120, cadenceSpm: 120, status: "accepted" },
    ],
  };
}

function validCadenceAnalysisSeriesWithSampleCount(sampleCount: number): Record<string, unknown> {
  return {
    source: "phoneSensorEstimated",
    confidence: "low",
    samples: Array.from({ length: sampleCount }, (_, index) => ({
      elapsedSeconds: index,
      cadenceSpm: 95 + (index % 20),
      status: "accepted",
    })),
  };
}

function lowDataPayload(): Record<string, unknown> {
  return {
    clientRunSessionId: "low-data-local-session-001",
    startedAt: "2026-06-14T09:00:00.000Z",
    completedAt: "2026-06-14T09:00:02.000Z",
    durationSeconds: 2,
    distanceMeters: 0,
    avgPaceSecondsPerKm: 0,
    source: "mobile",
    routePrivacy: "private",
  };
}

function pausedRunPayload(): Record<string, unknown> {
  return {
    clientRunSessionId: "paused-local-session-001",
    startedAt: "2026-06-14T09:00:00.000Z",
    completedAt: "2026-06-14T10:05:00.000Z",
    durationSeconds: 3207,
    activeDurationSeconds: 3207,
    elapsedWallSeconds: 3900,
    pausedDurationSeconds: 693,
    distanceMeters: 8460,
    avgPaceSecondsPerKm: 379,
    source: "mobile",
    routePrivacy: "private",
  };
}

function runPayloadForSession(fields: {
  readonly clientRunSessionId: string;
  readonly startedAt: string;
  readonly completedAt: string;
  readonly durationSeconds?: number;
  readonly distanceMeters?: number;
  readonly avgPaceSecondsPerKm?: number;
}): Record<string, unknown> {
  return {
    ...validPayload(),
    ...fields,
  };
}

function validPayloadWithout(fieldName: string): Record<string, unknown> {
  const payload = validPayload();
  delete payload[fieldName];
  return payload;
}

type TestPlanWorkout = {
  readonly scheduledWorkoutId: string;
  readonly dayLabel: string;
  readonly title: string;
  readonly kind: string;
  readonly durationMinutes?: number;
  readonly targetDistanceMeters?: number;
};

function durationWorkout(fields: {
  readonly scheduledWorkoutId: string;
  readonly dayLabel: string;
  readonly durationMinutes: number;
}): TestPlanWorkout {
  return {
    scheduledWorkoutId: fields.scheduledWorkoutId,
    dayLabel: fields.dayLabel,
    durationMinutes: fields.durationMinutes,
    title: "Easy Run",
    kind: "run",
  };
}

function distanceWorkout(fields: {
  readonly scheduledWorkoutId: string;
  readonly dayLabel: string;
  readonly targetDistanceMeters: number;
}): TestPlanWorkout {
  return {
    scheduledWorkoutId: fields.scheduledWorkoutId,
    dayLabel: fields.dayLabel,
    targetDistanceMeters: fields.targetDistanceMeters,
    title: "Long Run",
    kind: "run",
  };
}

function restWorkout(fields: {
  readonly scheduledWorkoutId: string;
  readonly dayLabel: string;
}): TestPlanWorkout {
  return {
    scheduledWorkoutId: fields.scheduledWorkoutId,
    dayLabel: fields.dayLabel,
    title: "Rest Day",
    kind: "rest",
  };
}

async function writeGeneratedPlanWithWorkouts(
  workouts: readonly TestPlanWorkout[],
  options: { readonly planId?: string } = {},
): Promise<void> {
  await firestore.doc(`generatedPlans/${USER_UID}`).set({
    planId: options.planId ?? "generated-plan-001",
    startsOnDate: "2026-06-15",
    createdAt: "2026-06-15T00:05:00.000Z",
    updatedAt: "2026-06-15T00:05:00.000Z",
    weeks: [
      {
        weekNumber: 1,
        workouts: workouts.map((workout) => ({
          scheduledWorkoutId: workout.scheduledWorkoutId,
          dayLabel: workout.dayLabel,
          title: workout.title,
          kind: workout.kind,
          ...(workout.durationMinutes === undefined ? {} : { durationMinutes: workout.durationMinutes }),
          ...(workout.targetDistanceMeters === undefined
            ? {}
            : {
                objectiveKind: "distance",
                targetDistanceMeters: workout.targetDistanceMeters,
              }),
        })),
      },
    ],
  });
}

async function expectRejectsCode(action: () => Promise<unknown>, code: string): Promise<void> {
  await assert.rejects(action, (error: unknown) => {
    assert.equal(getErrorCode(error), code);
    return true;
  });
}

function getErrorCode(error: unknown): string {
  if (typeof error === "object" && error !== null && "code" in error) {
    const code = error.code;
    if (typeof code === "string") {
      return code;
    }
  }

  return "";
}

async function clearCollections(collectionNames: readonly string[]): Promise<void> {
  await Promise.all(
    collectionNames.map(async (collectionName) => {
      const snapshot = await firestore.collection(collectionName).get();
      await Promise.all(snapshot.docs.map((document) => document.ref.delete()));
    }),
  );
}

async function countDocuments(collectionName: string): Promise<number> {
  const snapshot = await firestore.collection(collectionName).get();
  return snapshot.size;
}
